Решение задания 3-2#8
BylaniiSergey/TKI-141TFour pull request #14
Opened 2023-11-02 09:07 UTC by BylaniiSergey

2023-11-02 10:03 UTC, BalakinaEP requested changes
В данный работе необходимо использовать рекуррентное уравнение для вычисления. Факториал нам не нужен

2023-11-03 18:30 UTC, BalakinaEP requested changes

2023-11-03 18:30 UTC, BalakinaEP commented on Tasks 3-2/Task 3-2/main 3-2.c
> +	return pow(k + 1, 3) / pow(k, 4);
У Вас в задании ошибка. У Вас не знакопеременный ряд. Нужно добавить (-1)^k

2023-11-03 18:30 UTC, BalakinaEP commented on Tasks 3-2/Task 3-2/main 3-2.c
> +	while (sum < epsilon)
Погрешность суммы оценивается первым отброшенным членом

2023-11-07 11:51 UTC, MarinaPaley approved these changes

2023-11-07 11:53 UTC, merged