Решение задания 4-1#10
BylaniiSergey/TKI-141TFour pull request #25
Opened 2023-11-28 08:58 UTC by BylaniiSergey

2023-11-28 10:55 UTC, BalakinaEP requested changes

2023-11-28 10:55 UTC, BalakinaEP commented on Tasks 4-1/Task 4-1/main 4-1.c
> +        perror("Неудалось выделить память под массив!\n");
```
perror("Не удалось выделить память под массив!\n");
abort();

```

2023-11-28 10:55 UTC, BalakinaEP commented on Tasks 4-1/Task 4-1/main 4-1.c
> +        perror("Неверный выбор!\n");
abort();

2023-11-28 10:55 UTC, BalakinaEP commented on Tasks 4-1/Task 4-1/main 4-1.c
> +    return 1;
void

2023-11-28 10:55 UTC, BalakinaEP commented on Tasks 4-1/Task 4-1/main 4-1.c
> +    int* arr_k = init_array(size);
k перенести сюда

2023-11-28 10:55 UTC, BalakinaEP commented on Tasks 4-1/Task 4-1/main 4-1.c
> +    size_t k = get_size("Введите k: ");
В функцию

2023-11-28 10:55 UTC, BalakinaEP commented on Tasks 4-1/Task 4-1/main 4-1.c
> +    print_array(size, arr_1);
`print_array(size,  replace_last_k(arr, size, k));`

2023-11-28 10:55 UTC, BalakinaEP commented on Tasks 4-1/Task 4-1/main 4-1.c
> +    int checkSum = get_value("Введите сумму элементов: ");
sum в функцию

2023-11-28 10:55 UTC, BalakinaEP commented on Tasks 4-1/Task 4-1/main 4-1.c
> +}
это только печать true или false
isCoupleSum отдельная функция, которая проверяет (bool) возвращает  true или false

2023-12-01 06:59 UTC, BalakinaEP requested changes

2023-12-01 06:59 UTC, BalakinaEP commented on Tasks 4-1/Task 4-1/main 4-1.c
> +};
Документация

2023-12-01 06:59 UTC, BalakinaEP commented on Tasks 4-1/Task 4-1/main 4-1.c
> +int* replace_last_k(const int* const arr, size_t size, size_t k)
Зачем тогда сюда передавать k?

2023-12-01 06:59 UTC, BalakinaEP commented on Tasks 4-1/Task 4-1/main 4-1.c
> +    memcpy(arr_k, arr, size * sizeof(int));
Зачем это? Вы же здесь работаете в другом массиве

2023-12-07 11:49 UTC, BalakinaEP requested changes

2023-12-07 11:49 UTC, BalakinaEP commented on Tasks 4-1/Task 4-1/main 4-1.c
> +        int next = array[i + 1];
Выход за пределы массива

2023-12-07 11:49 UTC, BalakinaEP commented on Tasks 4-1/Task 4-1/main 4-1.c
> +    const int maximum_limit = get_value("Введите верхнюю границу массива: ");
Здесь и выше это одинаковый код. Нужно убрать ее в фукнцию  fill_array

2023-12-07 11:49 UTC, BalakinaEP commented on Tasks 4-1/Task 4-1/main 4-1.c
> +    int* arr_1 = replace_last_k(arr, size, k);
Рекурсия?

2023-12-08 14:43 UTC, BylaniiSergey commented on Tasks 4-1/Task 4-1/main 4-1.c
> +        int next = array[i + 1];
я же создал size-1, почему выход за границы

2023-12-11 14:17 UTC, BalakinaEP requested changes

2023-12-11 14:17 UTC, BalakinaEP commented on Tasks 4-1/Task 4-1/main 4-1.c
> +    enum random_or_keybord choice = get_value("Выберите нужный вариант: ");
неправильно производите явное преобразование

2023-12-11 14:17 UTC, BalakinaEP commented on Tasks 4-1/Task 4-1/main 4-1.c
> +}
Зачем эта процедура возвращает int? Вы где-то это проверяете?

2023-12-11 14:17 UTC, BalakinaEP commented on Tasks 4-1/Task 4-1/main 4-1.c
> +    if (is_couple_sum(size, array, checkSum))
Сдается мне, что тут опечатка. Ваш код вообще не должен собираться

2023-12-11 14:17 UTC, BalakinaEP commented on Tasks 4-1/Task 4-1/main 4-1.c
> +        array[i] = minimum_limit + rand() % (maximum_limit - minimum_limit + 1);
А откуда эта функция узнала minimum_limit и maximum_limit?
Нерабочий код!

2023-12-11 14:17 UTC, BalakinaEP commented on Tasks 4-1/Task 4-1/main 4-1.c
> +    const int maximum_limit = get_value("Введите верхнюю границу массива: ");
Это нужно убрать в main

2023-12-11 14:17 UTC, BalakinaEP commented on Tasks 4-1/Task 4-1/main 4-1.c
> +    }
Это отдельная функция

2023-12-12 08:20 UTC, BalakinaEP requested changes
Возможно когда-нибудь вы начнете проверять свой код на работоспособность!

2023-12-12 08:20 UTC, BalakinaEP commented on Tasks 4-1/Task 4-1/main 4-1.c
> +    if (is_couple_sum(size, array))
В это функции опечатка и у нее 3 параметра, а не 2

2023-12-12 08:20 UTC, BalakinaEP commented on Tasks 4-1/Task 4-1/main 4-1.c
> +        perror("Неудалось выделить память под массив!\n");
Трудно вставить пробел?
Не с глаголом пишется раздельно!

2023-12-12 08:20 UTC, BalakinaEP commented on Tasks 4-1/Task 4-1/main 4-1.c
> +    enum random_or_keyboard choice = (enum random_or_keyboard)get_value("Введите нужный элемент: ");
Эта строка по-прежнему не собирается. В ней опечатка

2023-12-21 12:30 UTC, MarinaPaley requested changes

2023-12-21 12:30 UTC, MarinaPaley commented on Tasks 4-1/Task 4-1/main 4-1.c
> +#include <math.h>
проверить, нужна ли...

2023-12-21 12:30 UTC, MarinaPaley commented on Tasks 4-1/Task 4-1/main 4-1.c
> +
`int* second_array = replace_last_k(arr, size);`

2023-12-21 12:30 UTC, MarinaPaley commented on Tasks 4-1/Task 4-1/main 4-1.c
> +
Течет память. Нужно удалить массивы

2023-12-21 12:30 UTC, MarinaPaley commented on Tasks 4-1/Task 4-1/main 4-1.c
> +    if (minimum_limit >= maximum_limit)
`return minimum_limit >= maximum_limit;`

2023-12-25 10:39 UTC, BalakinaEP requested changes

2023-12-25 10:39 UTC, BalakinaEP commented on Tasks 4-1/Task 4-1/main 4-1.c
> +    fill_array(size, arr, minimum_limit, maximum_limit);
не проверили, что минимум меньше максимума

2023-12-25 10:39 UTC, BalakinaEP commented on Tasks 4-1/Task 4-1/main 4-1.c
> +    fill_array(size, arr, minimum_limit, maximum_limit);
Не исправили

2023-12-25 10:39 UTC, BalakinaEP commented on Tasks 4-1/Task 4-1/main 4-1.c
> +    delete_array(second_array);
Освобождайте память сразу как закончили работать с этим массивом. Эта строка должна быть выше

2023-12-25 10:39 UTC, BalakinaEP commented on Tasks 4-1/Task 4-1/main 4-1.c
> +        free(arr);
нужно еще присвоить arr NULL

2023-12-25 10:39 UTC, BalakinaEP commented on Tasks 4-1/Task 4-1/main 4-1.c
> +    }
Это отдельная функция, убрать ее вызов в main

2023-12-25 11:12 UTC, BalakinaEP requested changes

2023-12-25 11:12 UTC, BalakinaEP commented on Tasks 4-1/Task 4-1/main 4-1.c
> +    for (size_t i = size ; i < size; ++i)
`for (size_t i = size -1 ; i >= size - 1 - k; ++i) `

2023-12-25 13:59 UTC, MarinaPaley requested changes

2023-12-25 13:59 UTC, MarinaPaley commented on Tasks 4-1/Task 4-1/main 4-1.c
> +#include <float.h>
для каких целей?

2023-12-25 13:59 UTC, MarinaPaley commented on Tasks 4-1/Task 4-1/main 4-1.c
> +void delete_array(int* arr);
```c
void delete_array(int** array)
{
    if(NULL != array);
    {
        free(array);
    }

    array = NULL;
}

2023-12-25 13:59 UTC, MarinaPaley commented on Tasks 4-1/Task 4-1/main 4-1.c
> +        int c = get_value("");
`int value = ...`

2023-12-25 13:59 UTC, MarinaPaley commented on Tasks 4-1/Task 4-1/main 4-1.c
> +    int a;
`int value = ...`

2023-12-25 14:47 UTC, MarinaPaley approved these changes

2023-12-28 03:42 UTC, merged