Решение задания 4-2#11
BylaniiSergey/TKI-141TFour pull request #29
Opened 2023-12-03 12:50 UTC by BylaniiSergey

2023-12-05 11:17 UTC, BalakinaEP requested changes
кодировка

2023-12-25 14:03 UTC, MarinaPaley requested changes

2023-12-25 14:03 UTC, MarinaPaley commented on 4-2/4-2/4-2.c
> +#include <float.h>
Скорее всего не нужны

2023-12-25 14:03 UTC, MarinaPaley commented on 4-2/4-2/4-2.c
> +	return 1;
не нужно

2023-12-25 14:03 UTC, MarinaPaley commented on 4-2/4-2/4-2.c
> +int fill_random(const size_t size, int* array)
`void`

2023-12-25 14:03 UTC, MarinaPaley commented on 4-2/4-2/4-2.c
> +int print_array(const size_t size, const int* array)
`void`

2023-12-25 14:03 UTC, MarinaPaley commented on 4-2/4-2/4-2.c
> +	return 1;
не нужно

2023-12-25 14:03 UTC, MarinaPaley commented on 4-2/4-2/4-2.c
> +	int a;
`int value = ..`

2023-12-25 14:03 UTC, MarinaPaley commented on 4-2/4-2/4-2.c
> +	memcpy(new_array, array, (last_divisible_index + 1) * sizeof(int));
Напишите свою реализацию

2023-12-27 21:28 UTC, MarinaPaley approved these changes
УБЕРИТЕ неиспользуемые инклюды!!!

2023-12-27 21:28 UTC, MarinaPaley commented on 4-2/4-2/4-2.c
> +#include <memory.h>
Избыточный заголовок. Включая заголовок, Вы должны осознавать, что [текстовый препроцессор](https://ru.wikipedia.org/wiki/Препроцессор_Си) заменит директиву [`#include`](https://en.cppreference.com/w/cpp/preprocessor/include) на ПОЛНОЕ содержимое файла, указанного в директиве в качестве целевого.

> Including a header file produces the same results as copying the header file into each source file that needs it. Such copying would be time-consuming and error-prone.

https://gcc.gnu.org/onlinedocs/gcc-3.0.2/cpp_2.html

Препроцессор языка C и препроцессор языка C++ работают схожим образом, так как язык C++ эволюционно происходит от языка C. [Бьёрн Страуструп](https://ru.wikipedia.org/wiki/Страуструп,_Бьёрн) работал в той же [лаборатории Белла](https://ru.wikipedia.org/wiki/Лаборатории_Белла) в [AT&T](https://ru.wikipedia.org/wiki/AT%26T), что и [Денис Ритчи](https://ru.wikipedia.org/wiki/Ритчи,_Деннис).

2023-12-27 21:28 UTC, MarinaPaley commented on 4-2/4-2/4-2.c
> +#include <float.h>
Уберите!

2023-12-28 03:42 UTC, merged